# Generated by Django 2.2.3 on 2019-09-20 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('nwankwochibikescrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectroles',
            unique_together={('user', 'project', 'role')},
        ),
    ]
