# Generated by Django 2.2.3 on 2019-09-20 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwankwochibikescrumy', '0002_auto_20190920_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectroles',
            unique_together={('user', 'project')},
        ),
    ]
