# Generated by Django 2.2.3 on 2019-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwankwochibikescrumy', '0002_auto_20190802_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
