# Generated by Django 2.2.3 on 2019-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwankwochibikescrumy', '0003_scrumuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
