# Generated by Django 2.2.3 on 2019-09-24 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwankwochibikescrumy', '0003_auto_20190920_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
