# Generated by Django 2.2.3 on 2019-09-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwankwochibikescrumy', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='nwankwochibikescrumy.Project'),
            preserve_default=False,
        ),
    ]
