# Generated by Django 2.2.3 on 2019-09-20 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwankwochibikescrumy', '0009_auto_20190917_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='nwankwochibikescrumy.ProjectRoles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwankwochibikescrumy.Project'),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='projectroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
